### ISSUE TITLE
Mission: Run a MetaCartel Meetup

### ISSUE THREAD

**Issue by pet3r-pan** [metacartel/mission#1]
**Objective:** Run a local meetup in your crypto-community focused on educating others on DAOs and the greater world of MetaCartel.

**Reward:** The MetaCartel DAO will consider you for DAO membership as a show of faith in-return for your heroic efforts.

**What should the meetup be about?**

Really anything that is within the scope of the following:
- Introduction to DAOs, what they are and various DAOs in the ecosystem
- Introduction to MetaCartel's grant funding program and various community projects
- All things DAOs / DApps + MetaCartel grantee projects

**An example structure for a meetup:** 
- [15 mins] Presentation: Intro to DAOs (Moloch DAO, MetaCartel DAO, Venture DAO, etc.)
- [15 mins] Guest MetaCartel speaker dialing in remotely or in real life 
- [30mins] Panel presentation of choice

This is just an example, be creative as you wish!

**I want to do this, how I get to start?**
Message @ pet3rpan on telegram, we'll brainstorm on the meetup agenda and we'll then ship some MetaCartel stickers over to you :)

**Comment by YalorMewn** [comment]
Are you looking for any specific deliverables, IE: Should it be recorded, or live streamed, or just some photos, do you want to approve any slides that tributes put together ? 

Also where can you find stats like how much funding has been given, what are some of the countries members live in, the list of projects integrated into the Cartel, etc.

I would personally be stoked to do this in Jackson Hole, Wy (a very crypto friendly State) 🤠

**Comment by pet3r-pan** [comment]
@YalorMewn Yes! Good suggestions: Photos would be A+

Also you can find those details all on the metacartel.org website + medium publication, maybe need some digging around, however. Bonus points for aggregating a small list while you do so :)

**Comment by yeqbfgxjiq** [comment]
I'd like to suggest that the example structure for said meetup includes a workshop session where people can get help deploying and using DAOs.

**Comment by jadbox** [comment]
Hey folks, I heard from the Tuesday call that virtual conference software may be needed to organize meetups, especially with COVID-19 causing cancellations. Oddly enough, the last two years I created online platforms that organize connect people with different ideas for meaningful online discussions.

Dinnertable Chat is an online chatroulette-style conference matchmaking system based on mixing people based on same and different viewpoints. After each session, users rate each other based on simple discussion qualities (respectful and friendly) and then get matched based on similar 'positivity' stat levels. The same idea could be used to mix people on any category (by skill, field, etc): https://www.dinnertable.chat/about

I'm not a member yet of MC, but I'd love to see how I could help the DAO via my past work so that I can join the movement!

**Comment by jadbox** [comment]
Hey folks, I heard from the Tuesday call that virtual conference software may be needed to organize meetups, especially with COVID-19 causing cancellations. Oddly enough, the last two years I created online platforms that organize people to have 

Online chatroulette-style matching based on mixing people based on viewpoints. The same idea could be used to mix people on any category (by skill, field, etc):
https://www.dinnertable.chat/about

This software matches people in physical spaces by dividing people up into groups, such that each group has _maximized_ viewpoint diversity of each of the members. I could also adapt this to be applied to online conferencing and maximize on both diversity as well as interests (based on weights).
https://www.mixopinions.com/

Some of the philosophy of why I was focusing on 'mixed viewpoint' conference software:
https://docs.google.com/presentation/d/1Q5KWhxhBMLWSvrYoEoWPWAO-YqgPwGRakvRNUnxtz1M/edit?usp=sharing

I'm not a member yet of MC, but I'd love to see how I could help the DAO via my past work so that I can join this movement.
